#Blacklist animals which will never despawn.
#Format for every entry is "<namespace>:<path>". Tags are supported, must be in the format of "#<namespace>:<path>". Namespace may be omitted to use "minecraft" by default. May use asterisk as wildcard parameter via pattern matching, e.g. "minecraft:*_shulker_box" to match all shulker boxes no matter of color.
animal_blacklist = ["whisperwoods:hirschgeist"]
#Constant for determining when to stop spawning animals in a world. Normally set to 10, monster constant is 70 for comparison. 18 is chosen to mimic spawning mechanics of the beta era.
#Range: > -2147483648
animal_mob_cap = 18
#Make all mobs (not just animals) automatically persistent when spawned using the "/summon" command, a spawn egg or a dispenser.
summoned_mob_persistence = false

